// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA51ozzUo1FzA1rFBP6gVKgu6HsRRI41fI',
    appId: '1:316891399377:web:08d82da030e3c6bd4531f0',
    messagingSenderId: '316891399377',
    projectId: 'memorymap-a49c4',
    authDomain: 'memorymap-a49c4.firebaseapp.com',
    storageBucket: 'memorymap-a49c4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe5q46-S8k-C5xWSgHEeUQqF9SQxnaA54',
    appId: '1:316891399377:android:6177ae3cd5bd5fc54531f0',
    messagingSenderId: '316891399377',
    projectId: 'memorymap-a49c4',
    storageBucket: 'memorymap-a49c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpAQ0d6SJi-7FGucSngL78zCHccPya6TM',
    appId: '1:316891399377:ios:8631e936feb8a5284531f0',
    messagingSenderId: '316891399377',
    projectId: 'memorymap-a49c4',
    storageBucket: 'memorymap-a49c4.firebasestorage.app',
    iosBundleId: 'com.bakicanozen.memoryMap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpAQ0d6SJi-7FGucSngL78zCHccPya6TM',
    appId: '1:316891399377:ios:8631e936feb8a5284531f0',
    messagingSenderId: '316891399377',
    projectId: 'memorymap-a49c4',
    storageBucket: 'memorymap-a49c4.firebasestorage.app',
    iosBundleId: 'com.bakicanozen.memoryMap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA51ozzUo1FzA1rFBP6gVKgu6HsRRI41fI',
    appId: '1:316891399377:web:5236e536fd3298ea4531f0',
    messagingSenderId: '316891399377',
    projectId: 'memorymap-a49c4',
    authDomain: 'memorymap-a49c4.firebaseapp.com',
    storageBucket: 'memorymap-a49c4.firebasestorage.app',
  );

}